### ISSUE TITLE
Precipitation contours

### ISSUE THREAD

**Issue by pdirmeyer** [lorendoyle/clim680#1]
Precipitation is a field where linear color scales do not work well – You can specify specific levels for the contours (see the [matplotlib contourf documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.contourf.html)). For precipitation, powers of two work well (e.g., 0.5, 1, 2, 4, 8, 16, 32 mm/day).

**Comment by lorendoyle** [comment]
I specified the levels in powers of two for the precipitation contours. The units are in meters/hour because those are the units of the data.
