### ISSUE TITLE
[Assignment 1] - lingering issues

### ISSUE THREAD

**Issue by pdirmeyer** [lorendoyle/clim680#10]
Two things that could still be improved for assignment 1:

1. The units could be changed to something less peculiar - instead of m/hour, your could multiply by 1000 for mm/hour, or better yet 24000 for mm/day, which is quite commonly used.

2. The contour interval is better, but by default `matplotlib` tries to distribute the colors linearly across the range of values despite the contour interval you choose.  That is why you still have so much purple and blue.  You can explicitly specify the colors for each contour interval - Chang had this problem, you can see what he did here: https://github.com/shueze/clim680/blob/master/PM10.ipynb.

**Comment by lorendoyle** [comment]
I redid the homework using the dataset I used for the project (updated as hw1_corrections_new_update.ipynb), and the units were no longer an issue in this case. And because I am working on a smaller region, I think that fixed the color level issue I was having as well.
