### ISSUE TITLE
[Assignment 2] Lingering Issues

### ISSUE THREAD

**Issue by luisortizuriarte** [lorendoyle/clim680#11]
Similar to the issue in your Assignment 1, the precipitation colormap could use some work. 

The issue is that even though your specifying a non-linearly distributed set of contour boundaries Matplotlib will still map those out linearly to the colormap. You can modify that mapping by changing the "norm". As Paul pointed out in [Lingering Issues for Assignment 1](https://github.com/lorendoyle/clim680/issues/10), you can look at how [Chang addressed this](https://github.com/shueze/clim680/blob/master/PM10.ipynb) for ideas.

**Comment by lorendoyle** [comment]
I redid the homework using the dataset from my project (updated in my repository as hw2_corrections_new_update.ipynb), as I deleted the dataset I originally used. Because the dataset is over a smaller region, I don't believe the precipitation colormap is an issue anymore.
