### ISSUE TITLE
[Assignment 3] Tidying up after data exploration

### ISSUE THREAD

**Issue by luisortizuriarte** [lorendoyle/clim680#7]
In your submitted notebook, you dedicate a lot of cells to exploratory analysis with various outputs printed out. As you work and start resolving your issues, either remove erroneous code or consolidate it into single cells with fewer printouts. This will help you avoid duplication and errors and make it easier to document as well.

**Comment by lorendoyle** [comment]
I removed the cells I no longer needed, and updated my documentation.
